### ISSUE TITLE
Identify Subgroups

### ISSUE THREAD

**Issue by chemGoggles** [vivo-community/vivo-graphql#6]
- UI Design Subgroup
- Data Design Subgroup
- Front End Development Subgroup
- Back End Implementation Subgroup

**Comment by outten45** [comment]
Looks good to me. There might be some blurring between people doing the front end and back end, but this is probably good. :+1:

**Comment by delsborg** [comment]
Agree with Richard. This is a good place to start. Would be good to identify the reference for each group.
I'll take a stab at it below:

back end -- the API layer that consists of the underlying data model and the data service. This delivers the json data package which will be the reference interface between the front end and the back end. The json data package.

data design: this could mean a few things. Is it the design of the data in the underlying model, in this case elastic? Is it the design of the json data package/payload spec that is delivered by the back end API? The later seems crucial because the backend and frontend groups, along with possibly the UI group need to agree on a data interface reference spec.

Front end: The technology stack used to render a webpage. This stack will consume and display data on a web client which is delivered from the Back End according to the data design reference spec. The front end is responsible for component level objects that process events into back end calls and render into front end data objects.

UI Design: Look, feel, accessibility of the front end. CSS design. Rendering of front end objects into modern stylistic visually appealing web pages.

**Comment by outten45** [comment]
Hi @delsborg - Maybe to help clarify a few things (at least for me).

**Back end** - yes :+1: 

**data design** - yes :+1: 

**Front end** - yes. this is the front end that talks to the API layer and implements the design from the **UI Design** group.

**UI Design** - yes, I think. It will also be about UX/information architecture and creating design assets (images etc). I could see some CSS coming out of the group with reusable components.

**Comment by chemGoggles** [comment]
Thanks @outten45 and @delsborg for the feedback.  I'll update the [logistics page](https://docs.google.com/document/d/14pDuRyZRvINklXiZdF-46idrVXobnaofuSpeuCaiWd0/edit#) with these descriptions.
